### ISSUE TITLE
Architecture changed on latest dockerhub release?

### ISSUE THREAD

**Issue by StellaASchlotter** [jmalloc/echo-server#17]
I noticed that the latest tag has a different architecture then the previous. This change breaks thing in a project i am working on. Was this intentional?

**Comment by jmalloc** [comment]
Oops, no it wasn't! Thanks for the report, I will fix this asap.

**Comment by jmalloc** [comment]
I have re-pushed the `0.3.0` and `latest` tags with the correct platform (`linux/amd64`), please reopen this issue if there are any further issues.
