### ISSUE TITLE
Add ability to skip initial message

### ISSUE THREAD

**Issue by lpinca** [jmalloc/echo-server#18]
The server sends an unsolicited initial WebSocket message https://github.com/jmalloc/echo-server/blob/b9eb3f7e4c3f319f97a38c4c9ad20025792d5448/cmd/echo-server/main.go#L106-L113

Would you be open to add an option to skip it?

Refs: https://github.com/markthethomas/ws-echo/issues/1

**Comment by jmalloc** [comment]
Hi, thanks for nice easy request :) I've added an option to control this behavior via an environment variable, and a request header in [v0.3.1](https://github.com/jmalloc/echo-server/releases/tag/v0.3.1).
