### ISSUE TITLE
Output shows a list of empty headers

### ISSUE THREAD

**Issue by pzwahlen** [jmalloc/echo-server#21]
Running this in a docker container and since the last update to 0.3.2, output shows as many empty header lines as actual headers (12 in this case)

![image](https://user-images.githubusercontent.com/11704985/178145730-d734b94b-05da-47d6-979d-9bb39c14a5a8.png)

**Comment by jmalloc** [comment]
Thank you, and apologies. This is fixed in [v0.3.3](https://github.com/jmalloc/echo-server/releases/tag/v0.3.3).
