### ISSUE TITLE
Echoed request line out of order

### ISSUE THREAD

**Issue by shtrom** [jmalloc/echo-server#22]
In https://github.com/jmalloc/echo-server/blob/695e6e6b79c4ed9616d3ff75a18674780918f2e7/cmd/echo-server/main.go#L254, the request line is echoed as ```HTTP-Version Method Request-URI```, while the RFC https://www.rfc-editor.org/rfc/rfc2616#section-5.1 states it is ```Method Request-URI HTTP-Version```

This confused me as I thought the reverse proxy I was trying to debug was mangling the request.

I realised when looking at the code that the line needs to be re-created from the request. I think it should be rebuilt in the expected order.

**Comment by jmalloc** [comment]
Nice catch! I never noticed >_<

This is fixed in v0.3.4, thanks.
