### ISSUE TITLE
How do you open a shell?

### ISSUE THREAD

**Issue by anthonybudd** [jmalloc/echo-server#23]
How do you open a shell?

`kubectl exec -ti POD /bin/bash` does not work

**Comment by jmalloc** [comment]
There is no OS/shell available, because the [Docker image](https://github.com/jmalloc/echo-server/blob/main/Dockerfile#LL1) is built [`FROM scratch`](https://hub.docker.com/_/scratch).

Is there's something you're trying to diagnose?
