### ISSUE TITLE
Support to config app root

### ISSUE THREAD

**Issue by omegazeng** [jmalloc/echo-server#24]
eg:
```bash
# start
PORT=8080 APP_ROOT=/app echo-server

# access
curl localhost:8080/app/
```
Thx.

**Comment by jmalloc** [comment]
Hi, thanks for the request. Can you explain why this is necessary? The server will respond to requests for any path.

**Comment by omegazeng** [comment]
> Hi, thanks for the request. Can you explain why this is necessary? The server will respond to requests for any path.

/.ws & /.sse must be in the root path.
I want to combine the echo server with other servers.

Like this:
/app > echo-server
/serverA > server a
/serverB > server b

**Comment by jmalloc** [comment]
Is this resolved by #32 ?

**Comment by jmalloc** [comment]
Or #35?

**Comment by jmalloc** [comment]
As of [v0.3.7](https://github.com/jmalloc/echo-server/releases/v0.3.7), the `.ws` and `.sse` endpoints are served from any "directory", which I believe solves this issue.

**Comment by omegazeng** [comment]
> As of [v0.3.7](https://github.com/jmalloc/echo-server/releases/v0.3.7), the `.ws` and `.sse` endpoints are served from any "directory", which I believe solves this issue.

it works!
thank you.
