### ISSUE TITLE
Status code '403' when trying to connect to wss://ws.ifelse.io/ via C# WebSocketClient (from 'GitHub' action workflow env.) 

### ISSUE THREAD

**Issue by Sergio1C** [jmalloc/echo-server#27]
Hi.
I am using your echo server (wss://ws.ifelse.io/) as a test to check my library for web-socket connection. The language is C# and I use .Net Framework 4.5 platform (there is some requirement to use deprecated stack). Internally I use [ClientWebSocket](https://learn.microsoft.com/en-us/dotnet/api/system.net.websockets.clientwebsocket?view=netframework-4.5) and all works fine from my local PC.

But, as I call the same (just establish websocket connection ) from the GitHub workflow (I have some simple CI test automation on GutHub) I got the following error:

`System.Exception: At method OpenConnection was occured exeption:The server returned status code '403' when status code '101' was expected.`

I can't have any idea of what causing this behaviour. I looked at the source code and didn't find any that could cause this. So maybe any suggestions or ideas I would give here. Thanks

**Comment by jmalloc** [comment]
I'm afraid I can't be of much help here, sorry.

I do not operate the server running on the `ifelse.io`, though I can see that it is up and accepting requests. I can only speculate that perhaps under GitHub actions there is some kind of proxy in place within the C# stack, but I really have no idea.
