### ISSUE TITLE
Versions on DockerHub, in addition to "latest"?

### ISSUE THREAD

**Issue by mccalluc** [jmalloc/echo-server#3]
Would you feel comfortable having version tags on DockerHub, in addition to latest? I don't expect the behavior will change radically, but I'm a bit more comfortable if dependencies are pinned.

**Comment by jmalloc** [comment]
I would like to address this in #7, thanks.

**Comment by jmalloc** [comment]
`jmalloc/echo-server:0.1.0` is tagged, currently equivalent to `latest`.
