### ISSUE TITLE
No headers are output

### ISSUE THREAD

**Issue by AceHack** [jmalloc/echo-server#4]
I don't see any headers get output

**Comment by jmalloc** [comment]
Are you referring to the logs by any chance?

To clarify how it's supposed to work, both the request headers and body are should be "echoed back" in the response body. 

For example, if I run:

    docker run --detach -P jmalloc/echo-server 
    curl http://127.0.0.1:32768 --include --request POST --data "This is the request body."

I get the following output:

```
HTTP/1.1 200 OK
Content-Type: text/plain
Date: Fri, 06 Mar 2020 23:20:11 GMT
Content-Length: 200

Request served by 4a32bdd877f6

HTTP/1.1 POST /

Host: 127.0.0.1:32768
Content-Type: application/x-www-form-urlencoded
User-Agent: curl/7.64.1
Accept: */*
Content-Length: 25

This is the request body.
```

It's not very clear from that, but the first set of headers are the servers *actual* response headers, as rendered by CURL. The line that reads `Request served by 4a32bdd877f6` is the beginning of the echo server's response body, which contains the request headers and the request body.

Here's what it looks like in my browser:

<img width="953" alt="echoserver" src="https://user-images.githubusercontent.com/761536/76130080-2bb52580-6055-11ea-8125-c4f37e86ab4b.png">

**Comment by AceHack** [comment]
Yes I’m referring to the logs.  I would really like to see the headers in the logs.

**Comment by jmalloc** [comment]
That seems useful. I've added #5 to track this as a feature request in case anyone wants to have a crack at a PR, but I won't get time myself any time soon. Cheers.
